export default defineEventHandler(async (event) => {
    return {
     mename: "กัญญารัตน์ สาระพันธ์",
     housenb: 506,
     group: 5,
     road: "มิตรภาพ",
     subdistrict: "ศิลา",
     district: "เมือง",
     province: "ขอนแก่น",
     zipcode: "40000",
     phonenb: '096555542365',
     age: 20,
     birthday: '02/05/2004',
     idcard: '1429900507767',
     idaccount: '06547855551',
     position: "อาจารย์",
     department: "การจัดการ",
     salary: 20050,
     stockvalue:1200,
     office:"สำนักงานธนาคารออมสิ้น",
     debt:30000,
     interest:'อัตราต่อปี 26%',
     guarantee:"ค้ำประกัน รถยนต์",
     remain:15000,
     accruedinterest:"ไม่มีดอกเบี้ย",
     reason:"กู้ยืมเงินเพื่อการประกอบอาชีพ",
     officer: "วีวี่ ยายี",
     chaiman: "พาลี บาลี",
     director: "ดาดา กากา",
      dateReceived: new Date().toISOString(),
    }
  });